env:
  es2021: true
  node: true
  browser: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/prefer-default-export: 'warn'
  import/no-extraneous-dependencies: [off, { devDependencies: true }]
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign: 0